const { test, expect } = require('@playwright/test');
const { artwork, addWork, workRow, exportBackup, ready, assertImageFaithful } = require('./helpers.cjs');

test('准备、排序、逐件主持、暂停、跳过、结束与回顾完整相连', async ({ page }) => {
  await page.goto('/');
  await expect(page.locator('#art-excluded')).toBeChecked();
  await page.locator('#show-title').fill('客厅里的春天');
  await page.locator('#host-name').fill('小画家');
  await addWork(page, { title: '第一件', words: '我先画这里。' });
  await addWork(page, { title: '第二件', words: '' });
  await addWork(page, { title: '先收好的作品', words: '这句话不给大家看。', included: false });
  await workRow(page, '第二件').locator('[data-action="up"]').click();
  await expect(page.locator('.artwork-row').first()).toContainText('第二件');
  await page.locator('#start-show').click();
  await expect(page.locator('#stage-title')).toHaveText('第二件');
  await expect(page.locator('#host-title')).toHaveText('客厅里的春天');
  await expect(page.locator('#host-view')).not.toContainText('先收好的作品');
  await page.locator('#host-note').fill('暂停前还没有完成的原话。');
  await page.locator('#host-pause').click();
  await expect(page.locator('#paused-message')).toBeVisible();
  await expect(page.locator('#host-next')).toBeDisabled();
  await page.reload();
  await ready(page);
  await page.locator('[data-view="host"]').first().click();
  await expect(page.locator('#paused-message')).toBeVisible();
  await expect(page.locator('#host-note')).toHaveValue('暂停前还没有完成的原话。');
  await page.locator('#host-pause').click();
  await page.locator('#host-skip').click();
  await expect(page.locator('#stage-title')).toHaveText('第一件');
  await page.locator('#host-note').fill('我想让大家看左边的小点。');
  await page.locator('#host-next').click();
  await expect(page.locator('#review-view')).toBeVisible();
  await expect(page.locator('#review-list')).toContainText('第二件');
  await expect(page.locator('#review-list')).toContainText('跳过');
  await expect(page.locator('#review-list')).toContainText('我想让大家看左边的小点。');
  await expect(page.locator('#review-view')).not.toContainText('先收好的作品');
  const backup = await exportBackup(page);
  expect(backup.artworks).toHaveLength(3);
  expect(backup.sessions.at(-1).status).toBe('ended');
  expect(backup.sessions.at(-1).records.map(record => record.title)).toEqual(['第二件', '第一件']);
  expect(backup.sessions.at(-1).records.map(record => record.status)).toEqual(['skipped', 'viewed']);
  expect(backup.sessions.at(-1).records[0].note).toBe('暂停前还没有完成的原话。');
});

test('可无照片办展；编辑、拒绝删除与确认删除都保持明确结果', async ({ page }) => {
  await page.goto('/');
  await addWork(page, { title: '摆在桌上的原作', words: '不需要照片。' });
  await workRow(page, '摆在桌上的原作').locator('[data-action="edit"]').click();
  await page.locator('#art-title').fill('改过名字的原作');
  await page.locator('#art-words').fill('我自己改的名字。');
  await page.locator('#save-artwork').click();
  await expect(page.locator('.artwork-row')).toHaveCount(1);
  await expect(workRow(page, '改过名字的原作')).toContainText('我自己改的名字。');
  page.once('dialog', dialog => dialog.dismiss());
  await workRow(page, '改过名字的原作').locator('[data-action="delete"]').click();
  await expect(page.locator('.artwork-row')).toHaveCount(1);
  await page.locator('#start-show').click();
  await expect(page.locator('#stage-art')).not.toHaveText('');
  await page.locator('#host-end').click();
  await expect(page.locator('#review-view')).toBeVisible();
  await page.locator('[data-view="prepare"]').first().click();
  page.once('dialog', dialog => dialog.accept());
  await workRow(page, '改过名字的原作').locator('[data-action="delete"]').click();
  await expect(page.locator('.artwork-row')).toHaveCount(0);
});

test('横竖图片、边缘标记、原话和三个打印组成保真；拒绝展示从所有输出排除', async ({ page }, testInfo) => {
  await page.goto('/');
  const words = '<script>window.unwanted = 1</script> & "原话"\n' + '我想按自己的顺序摆，也不想让别人替我改这句话。'.repeat(20);
  await addWork(page, { title: '横向原作', words, image: await artwork(page, 900, 300) });
  await addWork(page, { title: '竖向原作', words: '右上角的小方块不要切掉。', image: await artwork(page, 300, 900) });
  await addWork(page, { title: '秘密作品', words: '秘密原话不入展', included: false });
  await page.locator('#start-show').click();
  await expect(page.locator('#stage-words')).toHaveText(words);
  expect(await page.evaluate(() => window.unwanted)).toBeUndefined();
  await assertImageFaithful(page.locator('#stage-art img'), 900, 300);
  await page.locator('#host-next').click();
  await assertImageFaithful(page.locator('#stage-art img'), 300, 900);
  await page.locator('#host-next').click();
  await page.evaluate(() => { window.__printCalled = false; window.print = () => { window.__printCalled = true; }; });
  await page.locator('#print-show').click();
  expect(await page.evaluate(() => window.__printCalled)).toBe(true);
  await page.emulateMedia({ media: 'print' });
  const output = page.locator('#print-document');
  await expect(output).toBeVisible();
  await expect(output).toContainText(words);
  await expect(output).toContainText('展签');
  await expect(output).toContainText('主持');
  await expect(output).toContainText('回顾');
  await expect(output).not.toContainText('秘密作品');
  await expect(output).not.toContainText('秘密原话不入展');
  const images = output.locator('img');
  expect(await images.count()).toBeGreaterThanOrEqual(2);
  for (const image of await images.all()) {
    const ratio = await image.evaluate(img => img.naturalWidth / img.naturalHeight);
    await assertImageFaithful(image, ratio > 1 ? 900 : 300, ratio > 1 ? 300 : 900);
  }
  await page.screenshot({ path: testInfo.outputPath('print-preview.png'), fullPage: true });
});

test('曾经展示的作品撤回同意后，不再出现在历史回顾和打印快照', async ({ page }) => {
  await page.goto('/');
  await addWork(page, { title: '后来不愿展示的画', words: '后来不愿公开的原话' });
  await addWork(page, { title: '仍然愿意展示的画', words: '还可以看这张。' });
  await page.locator('#start-show').click();
  await page.locator('#host-note').fill('后来撤回的现场原话');
  await page.locator('#host-next').click();
  await page.locator('#host-next').click();
  await expect(page.locator('#review-list')).toContainText('后来不愿展示的画');
  await page.locator('[data-view="prepare"]').first().click();
  await workRow(page, '后来不愿展示的画').locator('[data-action="edit"]').click();
  await page.locator('#art-excluded').check();
  await page.locator('#save-artwork').click();
  await page.locator('[data-view="review"]').first().click();
  await expect(page.locator('#review-list')).not.toContainText('后来不愿展示的画');
  await expect(page.locator('#review-list')).not.toContainText('后来不愿公开的原话');
  await expect(page.locator('#review-list')).not.toContainText('后来撤回的现场原话');
  await page.evaluate(() => { window.print = () => {}; });
  await page.locator('#print-show').click();
  await expect(page.locator('#print-document')).not.toContainText('后来不愿展示的画');
  await expect(page.locator('#print-document')).not.toContainText('后来不愿公开的原话');
  await expect(page.locator('#print-document')).not.toContainText('后来撤回的现场原话');
  await expect(page.locator('#print-document')).toContainText('仍然愿意展示的画');
  await page.locator('[data-view="prepare"]').first().click();
  page.once('dialog', dialog => dialog.accept());
  await workRow(page, '后来不愿展示的画').locator('[data-action="delete"]').click();
  await page.locator('[data-view="review"]').first().click();
  await expect(page.locator('#review-list')).not.toContainText('后来不愿展示的画');
  await expect(page.locator('#review-list')).not.toContainText('后来撤回的现场原话');
  await page.locator('#print-show').click();
  await expect(page.locator('#print-document')).not.toContainText('后来不愿展示的画');
  await expect(page.locator('#print-document')).not.toContainText('后来不愿公开的原话');
  await expect(page.locator('#print-document')).not.toContainText('后来撤回的现场原话');
});
