import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Disclaimer — PolicyForge",
  description: "Important limitations and disclaimers for PolicyForge generated documents.",
};

export default function DisclaimerPage() {
  return (
    <div className="max-w-3xl mx-auto px-6 py-16">
      <h1 className="text-3xl font-semibold tracking-tight mb-6">Disclaimer</h1>

      <div className="prose prose-neutral dark:prose-invert max-w-none">
        <p>
          <strong>PolicyForge is a document-generation tool, not a law firm or compliance
          consultancy.</strong> The policies, procedures, and other documents generated by the
          service are templates and starting drafts only.
        </p>

        <h2>Not Legal or Compliance Advice</h2>
        <p>
          Nothing generated by PolicyForge constitutes legal, compliance, accounting, or audit
          advice. The content is provided for informational and drafting purposes only and
          should not be relied upon as a final submission to an auditor, regulator, or court.
        </p>

        <h2>Review Before Use</h2>
        <p>
          Generated documents should be reviewed, customized, and approved by your legal
          counsel, compliance consultant, or auditor before they are adopted, published, or
          submitted as part of a certification, audit, or regulatory filing.
        </p>

        <h2>No Certification or Guarantee</h2>
        <p>
          PolicyForge does not certify that any generated document will meet the requirements
          of SOC 2, ISO 27001, GDPR, HIPAA, or any other standard, law, or framework. We do not
          guarantee audit passage, certification, or regulatory approval.
        </p>

        <h2>Liability Limitation</h2>
        <p>
          To the maximum extent permitted by law, PolicyForge and its operators are not liable
          for any claim, loss, or damage arising from your use of or reliance on generated
          documents.
        </p>

        <h2>Questions</h2>
        <p>
          If you have questions about whether a generated document is appropriate for your
          situation, please consult a qualified professional. For service questions, contact{" "}
          <a href="mailto:hello@policyforge.io" className="text-primary hover:underline">
            hello@policyforge.io
          </a>
          .
        </p>
      </div>
    </div>
  );
}
